kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
spec:
  replicas: 2
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: artprod.dev.bloomberg.com/ngoehausen/sparknb:0.6
          command: ["/scripts/run_worker.sh", "spark-master-service"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
          securityContext:
            privileged: true